### ISSUE TITLE
translate dcps-0000 for Brazilian Portuguese

### ISSUE THREAD

**Issue by EvertonMelo** [decred/dcps#7]
Hi, 

what would be the best way to translate DCP-0000?
Decred Project have biggest Community on Brazil, but has little documentation in pt-br.

I see that if we translate the initial documents,
this can help in the presentation of the decred to more people.

**Comment by matheusd** [comment]
Hello Everton! If you're not there yet, join us at slack in the "Brazil" channel.

IMO, the DCPs are some of the *last* documentation that needs translation. They are highly technical and to understand them you need to be acquainted with deep aspects of the decred code and ecosystem. Pretty much anyone with that knowledge is going to be fluent in english.

So just going through the trouble of translating them to present as evidence of interest in the brazilian market is unnecessary at best, as the community is already pretty engaged here. 

Having said that, I **do** think we need higher level texts describing the purpose of a DCP before/during an onchain agenda voting, as that is of interest of stakeholders and many of them will be unable to understand the language and details of the more technical text. I did something kind of like that before the lnfeatures (DCPs 0002 & 0003) were activated and plan on doing that for the next ones.

**Comment by davecgh** [comment]
I agree with @matheusd's assessment.  There is certainly room for translation of a high-level description of the purpose of a DCP and why stakeholders may or may not want to vote for them.

However, the actual DCPs themselves are the de-facto technical specifications that multiple implementations and/or developers integrating the code will refer to.  There are, necessarily, a lot of very specific technical nuances in technical specifications that invariable do not translate well.

I've discussed with with various contractors and, thus far, everyone has agreed with this assessment as well.  Consequently, I'm going to go ahead and close this issue.
