### ISSUE TITLE
Update README and DCP-0000 to include Politeia

### ISSUE THREAD

**Issue by jholdstock** [decred/dcps#9]
Quote from `README.md`

>It is important to note that DCPs are intended to be the end result of an off-chain proposal and voting system that deals with more generalized proposal submissions. It is through that system that all initial proposals for consensus or protocol changes will be brought to life, undergo collaboration, and be subject to an initial community vote to determine if the work necessary to create a working implementation, its associated DCP, and an on-chain vote for the rule change should be performed.
>
> However, the aforementioned proposal system is not yet available. This document will be updated with more details once it is available.

This section can be updated now that Politeia is in [production](https://proposals.decred.org).

The same text also appears in `dcp-0000/dcp-0000.mediawiki`

**Comment by davecgh** [comment]
Good catch.
